SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE ='BASE TABLE'
ORDER BY TABLE_NAME;

SELECT COLUMN_NAME,
	   DATA_TYPE,
	   IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ='passengers';


SELECT COLUMN_NAME,
	   DATA_TYPE,
	   IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ='buses';

SELECT COLUMN_NAME,
	   DATA_TYPE,
	   IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ='bookings';
